language: c++
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:andykimpe/cmake3 -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake boost1.55
script: mkdir build && cd build && cmake -DBUILD_EXAMPLES=ON .. && make
