language: c++
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:andykimpe/cmake3 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get purge -y cmake
  - sudo apt-get install -y cmake3 boost1.55 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
script: mkdir build && cd build && cmake -DBUILD_EXAMPLES=ON .. && make
